# prettier-ignore
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    BuildLog

    Holds the lambda and s3 functions for the server

Globals:
    Function:
        Timeout: 60
        MemorySize: 128
        CodeUri: aws/lambda/
        Runtime: nodejs18.x
        Architectures: [x86_64]
        Environment:
            Variables:
                REGION_NAME: 'ap-southeast-2'
Resources:
    S3ImageUploaderFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: app.s3_image_uploader
            Policies: 
                - Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action: 's3:*'
                      Resource: '*'
            Events:
                S3ImageUploaderFunctionEvents:
                    Type: S3
                    Properties:
                        Bucket: !Ref SrcBucket
                        Events: s3:ObjectCreated:*
    SrcBucket:
        Type: AWS::S3::Bucket
# Outputs:
#     # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#     # Find out more about other implicit resources you can reference within SAM
#     # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#     ImageApi:
#         Description: 'API Gateway endpoint URL for Prod stage for ImageaApi function'
#         Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/image/'
#     S3ImageUploaderFunction:
#         Description: 'S3ImageUploaderFunction Lambda Function ARN'
#         Value: !GetAtt S3ImageUploaderFunction.Arn
